import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const Helvetica = localFont({
  src: "../public/font/RobotoFlex.ttf",
  variable: "--font-helvetica",
});

const Roboto = localFont({
  src: "../public/font/Roboto.ttf",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Higaurav | Full Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Helvetica.variable} ${Roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
